version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
      target: ${STAGE}
    image: shop_bot_bot:${STAGE}
    env_file: .env
    restart: on-failure
    stop_signal: SIGINT
    ports:
      - 80:80
      - 443:443
    networks:
      - default
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      django_server:
        condition: service_started

  django_server:
    build:
      context: .
      dockerfile: django_server.Dockerfile
      target: ${STAGE}
    image: shop_bot_django_server:${STAGE}
    env_file: .env
    restart: on-failure
    stop_signal: SIGINT
    ports:
      - ${DJANGO_PORT}:8000
    networks:
      - default
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:13
    env_file: .env
    restart: on-failure
    stop_signal: SIGINT
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    env_file: .env
    restart: on-failure
    stop_signal: SIGINT
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - default
    volumes:
      - redis_data:/data

networks:
  default:

volumes:
  postgres_data:
  redis_data:
