version: "3.9"

services:
  bot:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      django_server:
        condition: service_started

  django_server:
    depends_on:
      db:
        condition: service_healthy

  db:
    healthcheck:
      test: ["CMD", "/usr/bin/env", "PGPASSWORD=${POSTGRES_PASSWORD}",
             "pg_isready", "-h", "${POSTGRES_HOST}", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 0s

  redis:
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 0s
