# Generated by Django 3.2.3 on 2021-05-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(max_length=32, verbose_name="Название товара"),
                ),
                (
                    "thumb_url",
                    models.CharField(max_length=200, verbose_name="Ссылка на превью"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=255, null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="Telegram ID пользователя"
                    ),
                ),
                ("referral_id", models.IntegerField(null=True)),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Бюджет"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
